import Script from "next/script";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://cdn.ckeditor.com/ckeditor5/39.0.0/super-build/ckeditor.js"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
